// <auto-generated />
using System;
using LeaveTrack.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeaveTrack.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250802084851_mig_3")]
    partial class mig_3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeaveTrack.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Üretim Hattı",
                            IsDeleted = false,
                            Name = "Üretim"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Araştırma ve Geliştirme",
                            IsDeleted = false,
                            Name = "Ar-Ge"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kalite Kontrol",
                            IsDeleted = false,
                            Name = "Kalite"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Personel ve süreç yönetimi",
                            IsDeleted = false,
                            Name = "İnsan Kaynakları"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Makine ve sistem bakımı",
                            IsDeleted = false,
                            Name = "Bakım"
                        },
                        new
                        {
                            Id = 6,
                            Description = "IT Departmanı",
                            IsDeleted = false,
                            Name = "Bilgi İşlem"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Malzeme ve hizmet tedariki",
                            IsDeleted = false,
                            Name = "Satın Alma"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Finansal işlemler",
                            IsDeleted = false,
                            Name = "Finans"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Müşteri ilişkileri",
                            IsDeleted = false,
                            Name = "Satış"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Depolama ve taşıma",
                            IsDeleted = false,
                            Name = "Lojistik"
                        });
                });

            modelBuilder.Entity("LeaveTrack.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnnualLeaveLimit")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemUser")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            FullName = "Ali Balun",
                            IsDeleted = false,
                            IsSystemUser = true,
                            PasswordHash = "hashedpw1",
                            Role = 0,
                            Username = "ali.balun"
                        },
                        new
                        {
                            Id = 2,
                            AnnualLeaveLimit = 15,
                            DepartmentId = 2,
                            FullName = "Ayşe Yılmaz",
                            IsDeleted = false,
                            IsSystemUser = false,
                            PasswordHash = "hashedpw2",
                            Role = 1,
                            Username = "ayse.yilmaz"
                        },
                        new
                        {
                            Id = 3,
                            AnnualLeaveLimit = 18,
                            DepartmentId = 3,
                            FullName = "Mehmet Demir",
                            IsDeleted = false,
                            IsSystemUser = false,
                            PasswordHash = "hashedpw3",
                            Role = 1,
                            Username = "mehmet.demir"
                        },
                        new
                        {
                            Id = 4,
                            AnnualLeaveLimit = 14,
                            DepartmentId = 4,
                            FullName = "Zeynep Kaya",
                            IsDeleted = false,
                            IsSystemUser = false,
                            PasswordHash = "hashedpw4",
                            Role = 1,
                            Username = "zeynep.kaya"
                        },
                        new
                        {
                            Id = 5,
                            AnnualLeaveLimit = 20,
                            DepartmentId = 5,
                            FullName = "Emre Can",
                            IsDeleted = false,
                            IsSystemUser = false,
                            PasswordHash = "hashedpw5",
                            Role = 1,
                            Username = "emre.can"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 6,
                            FullName = "Burcu Aydın",
                            IsDeleted = false,
                            IsSystemUser = false,
                            PasswordHash = "hashedpw6",
                            Role = 1,
                            Username = "burcu.aydin"
                        },
                        new
                        {
                            Id = 7,
                            AnnualLeaveLimit = 22,
                            DepartmentId = 7,
                            FullName = "Deniz Yıldız",
                            IsDeleted = false,
                            IsSystemUser = false,
                            PasswordHash = "hashedpw7",
                            Role = 1,
                            Username = "deniz.yildiz"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 8,
                            FullName = "Kerem Öz",
                            IsDeleted = false,
                            IsSystemUser = false,
                            PasswordHash = "hashedpw8",
                            Role = 1,
                            Username = "kerem.oz"
                        },
                        new
                        {
                            Id = 9,
                            AnnualLeaveLimit = 16,
                            DepartmentId = 9,
                            FullName = "İlayda Çetin",
                            IsDeleted = false,
                            IsSystemUser = false,
                            PasswordHash = "hashedpw9",
                            Role = 1,
                            Username = "ilayda.cetin"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 10,
                            FullName = "Onur Güneş",
                            IsDeleted = false,
                            IsSystemUser = false,
                            PasswordHash = "hashedpw10",
                            Role = 1,
                            Username = "onur.gunes"
                        });
                });

            modelBuilder.Entity("LeaveTrack.Domain.Entities.Leave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("Leaves");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByUserId = 1,
                            EmployeeId = 2,
                            EndDate = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 1,
                            StartDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedByUserId = 1,
                            EmployeeId = 3,
                            EndDate = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 2,
                            StartDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedByUserId = 1,
                            EmployeeId = 4,
                            EndDate = new DateTime(2025, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 4,
                            StartDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedByUserId = 1,
                            EmployeeId = 5,
                            EndDate = new DateTime(2025, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 5,
                            StartDate = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedByUserId = 1,
                            EmployeeId = 6,
                            EndDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 6,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedByUserId = 1,
                            EmployeeId = 7,
                            EndDate = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 1,
                            StartDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedByUserId = 1,
                            EmployeeId = 8,
                            EndDate = new DateTime(2025, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 7,
                            StartDate = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedByUserId = 1,
                            EmployeeId = 9,
                            EndDate = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 8,
                            StartDate = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedByUserId = 1,
                            EmployeeId = 10,
                            EndDate = new DateTime(2025, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 3,
                            StartDate = new DateTime(2025, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedByUserId = 1,
                            EmployeeId = 2,
                            EndDate = new DateTime(2025, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 4,
                            StartDate = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedByUserId = 1,
                            EmployeeId = 3,
                            EndDate = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 1,
                            StartDate = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedByUserId = 1,
                            EmployeeId = 4,
                            EndDate = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 5,
                            StartDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreatedByUserId = 1,
                            EmployeeId = 5,
                            EndDate = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 8,
                            StartDate = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CreatedByUserId = 1,
                            EmployeeId = 6,
                            EndDate = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 2,
                            StartDate = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreatedByUserId = 1,
                            EmployeeId = 7,
                            EndDate = new DateTime(2025, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 4,
                            StartDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CreatedByUserId = 1,
                            EmployeeId = 8,
                            EndDate = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 1,
                            StartDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            CreatedByUserId = 1,
                            EmployeeId = 9,
                            EndDate = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 6,
                            StartDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            CreatedByUserId = 1,
                            EmployeeId = 10,
                            EndDate = new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 7,
                            StartDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            CreatedByUserId = 1,
                            EmployeeId = 1,
                            EndDate = new DateTime(2025, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 3,
                            StartDate = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            CreatedByUserId = 1,
                            EmployeeId = 2,
                            EndDate = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 4,
                            StartDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            CreatedByUserId = 1,
                            EmployeeId = 3,
                            EndDate = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 8,
                            StartDate = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            CreatedByUserId = 1,
                            EmployeeId = 4,
                            EndDate = new DateTime(2025, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 5,
                            StartDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            CreatedByUserId = 1,
                            EmployeeId = 5,
                            EndDate = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 1,
                            StartDate = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            CreatedByUserId = 1,
                            EmployeeId = 6,
                            EndDate = new DateTime(2025, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 2,
                            StartDate = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            CreatedByUserId = 1,
                            EmployeeId = 7,
                            EndDate = new DateTime(2025, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 6,
                            StartDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            CreatedByUserId = 1,
                            EmployeeId = 8,
                            EndDate = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 7,
                            StartDate = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            CreatedByUserId = 1,
                            EmployeeId = 9,
                            EndDate = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 3,
                            StartDate = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            CreatedByUserId = 1,
                            EmployeeId = 10,
                            EndDate = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 4,
                            StartDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            CreatedByUserId = 1,
                            EmployeeId = 1,
                            EndDate = new DateTime(2025, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 5,
                            StartDate = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            CreatedByUserId = 1,
                            EmployeeId = 2,
                            EndDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeaveTypeId = 1,
                            StartDate = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LeaveTrack.Domain.Entities.LeaveSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnualLeaveLimit")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("LeaveSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnnualLeaveLimit = 20,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("LeaveTrack.Domain.Entities.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Yıllık izin hakkı",
                            IsDeleted = false,
                            Name = "Yıllık İzin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sağlık nedeniyle izin",
                            IsDeleted = false,
                            Name = "Hastalık İzni"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Doğum yapan çalışanlar için izin",
                            IsDeleted = false,
                            Name = "Doğum İzni"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Maaşsız izin",
                            IsDeleted = false,
                            Name = "Ücretsiz İzin"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Evlilik nedeniyle verilen izin",
                            IsDeleted = false,
                            Name = "Evlilik İzni"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Yakın kaybı sonrası izin",
                            IsDeleted = false,
                            Name = "Cenaze İzni"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Görev nedeniyle verilen izin",
                            IsDeleted = false,
                            Name = "Görev İzni"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Yarım günlük izin",
                            IsDeleted = false,
                            Name = "Yarım Gün İzin"
                        });
                });

            modelBuilder.Entity("LeaveTrack.Domain.Entities.Employee", b =>
                {
                    b.HasOne("LeaveTrack.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("LeaveTrack.Domain.Entities.Leave", b =>
                {
                    b.HasOne("LeaveTrack.Domain.Entities.Employee", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeaveTrack.Domain.Entities.Employee", "Employee")
                        .WithMany("Leaves")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeaveTrack.Domain.Entities.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("LeaveTrack.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("LeaveTrack.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Leaves");
                });
#pragma warning restore 612, 618
        }
    }
}
